### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/beaver#4]
Hey @joewheaton what is this repo? It seems like it's housing an outdated copy of the sourcecode from the riverscapes template theme...

I was about to sort this out but I want to make sure I don't change something intentional.

**Comment by joewheaton** [comment]
Hey @MattReimer I think it is just an old repo I must have created with intent of having a beaver site a few years ago to migrate from beaver.joewheaton.org.  I will shut it down.
